### ISSUE TITLE
Nothing displayed when running app

### ISSUE THREAD

**Issue by mattStorer** [smart-on-fhir/cardiac-risk-app#5]
Hi -

I'm testing out this app, and have followed the deployment instructions.  After I execute "npm run serve," the server starts, and I can access the app at http://localhost:8000/.  There are no errors reported.  However, nothing is displayed to the screen and it's unclear why this is happening.

**Environment:**
OS: Ubuntu Linux 16.04.1 LTS (VirtualBox VM)
git: 2.7.4
npm: 3.5.2
cardiac-risk-app: 0.1.0

See attached files for details.  Please help!  Thanks!

![nothing_displayed](https://cloud.githubusercontent.com/assets/979938/23315059/5ba634fe-fa79-11e6-92e2-df0f9d0b79b0.png)
[run_log.txt](https://github.com/smart-on-fhir/cardiac-risk-app/files/800113/run_log.txt)
[nothing_displayed.html.txt](https://github.com/smart-on-fhir/cardiac-risk-app/files/800117/nothing_displayed.html.txt)

**Comment by mattStorer** [comment]
issue resolved

**Comment by elilambnz** [comment]
Hi @mattStorer, could you please provide some details of how you resolved this issue? I'm also experiencing this. Any help is much appreciated 😄
